/**
 * All Action Keys will go here
 */
const ACTION_KEYS = {
  PROPERTY_ADD_REQUEST: 'PROPERTY_ADD_REQUEST',
  PROPERTY_ADD_SUCCESS: 'PROPERTY_ADD_SUCCESS',
  PROPERTY_ADD_ERROR: 'PROPERTY_ADD_ERROR',

  REGSITER_TYPE: 'REGISTER_TYPE',
  STORE_AUTH: 'STORE_AUTH',
};

export default ACTION_KEYS;
