/**
 * All Action Keys will go here
 */
const ACTION_KEYS = {
  PROPERTY_ADD_REQUEST: 'PROPERTY_ADD_REQUEST',
  PROPERTY_ADD_SUCCESS: 'PROPERTY_ADD_SUCCESS',
  PROPERTY_ADD_ERROR: 'PROPERTY_ADD_ERROR',

  REGSITER_TYPE: 'REGISTER_TYPE',
  STORE_AUTH: 'STORE_AUTH',
  DOMAIN_SKILLS_LIST_REQUEST: 'DOMAIL_SKILLS_LIST_REQUEST',
  DOMAIN_SKILLS_LIST_SUCCESS: 'DOMAIL_SKILLS_LIST_SUCCESS',
  DOMAIN_SKILLS_LIST_FAILURE: 'DOMAIL_SKILLS_LIST_FAILURE',
  SUGGESTED_SERVICE_REQUEST: 'SUGGESTED_SERVICE_REQUEST',
  SUGGESTED_SERVICE_SUCCESS: 'SUGGESTED_SERVICE_SUCCESS',
  SUGGESTED_SERVICE_FAILURE: 'SUGGESTED_SERVICE_FAILURE',
  WINDOWLAYOUT: 'WINDOWLAYOUT',
  KYCSTEP1: 'KYCSTEP1',
  KYCSTEP2: 'KYCSTEP2',
  PROFESSIONAL_DETAILS: 'PROFESSIONAL_DETAILS',
  MENTOR_HEADING: 'MENTOR_HEADING',
  STUDENT_HEADING: 'STUDENT_HEADING',
}

export default ACTION_KEYS
